### PR TITLE
Code optimalisations

### PR DESCRIPTION
**Pull request by poespas**
There's a lot to fix in your code, especially the CSS and JS (external modules). But I feel like this is a good startup for some code optimalisations, if you have any questions about the changes, dont hesitate to ask! :)

### CODE REVIEW

**Comment by s-crypt** [comment]
Thank you for the contributions!

**Comment by s-crypt** [comment]
This breaks the counter.
Screenshot 2020-12-18 181425

**Comment by s-crypt** [comment]
@poespas please create a PR in the test branch if/when you get the problem fixed. Thank you! 😄

**Comment by poespas** [comment]
@s-crypt Could you not close the PR before it's actually done? 

Could you make sure your cache is cleared, when you test it? I changed the HTML class from `.dataDisplay` to `.data-display`. The styling works just fine for me locally, so the first thing that comes in mind is cache.

**Pull request merged**
